"""add_source_type

Revision ID: a2392e9be1b4
Revises: 5a35f2543804
Create Date: 2026-05-21 21:20:16.572647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2392e9be1b4'
down_revision: Union[str, None] = '5a35f2543804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitored_sources', sa.Column('source_type', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitored_sources', 'source_type')
    # ### end Alembic commands ###
